name: eatmore_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 0.17.3+1
  cupertino_icons: ^0.1.3
  flutter_icons: ^1.1.0
  scrollable_bottom_sheet: ^0.2.1
  charts_flutter: ^0.9.0
  google_maps_flutter: ^0.5.28+1
  flutter_switch: ^0.1.1
  dotted_border: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
